### ISSUE TITLE
.new? and ActiveFedora .exist? are broken with misplaced 400 errors.

### ISSUE THREAD

**Issue by flyingzumwalt** [cbeer/ldp#33]
[Ldp::Resource.new?](https://github.com/cbeer/ldp/blob/master/lib/ldp/resource.rb#L30-L34) and [ActiveFedora::FinderMethods.exists?](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/relation/finder_methods.rb#L87-L100) both raise this error when they should be returning false:

```
Ldp::HttpError:
       STATUS: 400 ... 
```

The underlying issue might be that Fedora is returning 400 when it should return 404, but either way, the methods are failing on the simple cases where an object doesn't exist and the code is checking whether it exists.

**Comment by jcoyne** [comment]
That's a perfectly legal character, provided you've configured Fedora correctly.  I'm not sure we can do anything better unless fcrepo is updated to give a better response
